version: "3.7"
services:
  submission-runner-docker:
    image: docker:dind
    privileged: true
    volumes:
      - "submission-runner-docker-certs:/certs/client"
      - "submission-runner-dind-data:/var/lib/docker"
    networks:
      dind:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
      TINI_SUBREAPER: "yes"
    restart: unless-stopped
    init: true
  submission-runner:
    image: aiwarssoc/submission-runner
    volumes:
      - "repositories:/home/subrunner/repositories"
      - "submission-runner-docker-certs:/certs/client:ro"
      - "./config.yml:/home/subrunner/config.yml:ro"
    networks:
      submission-runner:
        aliases:
          - runner
      dind:
    secrets:
      - secret_key
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_TLS_CERTDIR: "/certs"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    depends_on:
      - submission-runner-docker
    restart: unless-stopped
    init: true
  matchmaker:
    image: aiwarssoc/matchmaker
    volumes:
      - "./config.yml:/home/matchmaker/config.yml:ro"
    networks:
      submission-runner:
      database:
    depends_on:
      - submission-runner
      - database
    restart: unless-stopped
    init: true
  web-server:
    image: aiwarssoc/web-server
    networks:
      web-api:
      web-app:
    ports:
      - ${AIWARSOC_PORT}:80
    restart: unless-stopped
    init: true
  web-app:
    image: aiwarssoc/web-app
    networks:
      web-app:
        aliases:
          - web-app
    restart: unless-stopped
    init: true
  web-api:
    image: aiwarssoc/web-api
    volumes:
      - "repositories:/home/web_user/repositories"
      - "./config.yml:/home/web_user/config.yml:ro"
    networks:
      redis:
      database:
      submission-runner:
      web-api:
        aliases:
          - web-api
    secrets:
      - secret_key
    depends_on:
      - database
      - redis
    restart: unless-stopped
    init: true
  redis:
    image: redis
    volumes:
      - "redis-data:/data"
    command: "--appendonly yes"
    networks:
      redis:
        aliases:
          - redis
    restart: unless-stopped
  database:
    image: postgres
    volumes:
      - "database-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${AIWARSOC_DB_USERNAME}
      POSTGRES_PASSWORD: ${AIWARSOC_DB_PASSWORD}
    networks:
      database:
        aliases:
          - database
    restart: unless-stopped
    init: true
  adminer:
    image: adminer
    networks:
      - database

networks:
  redis:
  database:
  submission-runner:
  dind:
  web-api:
  web-app:
secrets:
  secret_key:
    file: ./secret.txt
volumes:
  repositories:
  redis-data:
  database-data:
  submission-runner-docker-certs:
  submission-runner-dind-data:
