services:
  submission-runner:
      - "./config.yml:/home/subrunner/config.yml:ro"
  web-server:
    ports:
      - "80:8080"
    volumes:
      - "./config.yml:/home/web_user/config.yml:ro"
  database:
    environment:
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
  adminer:
    ports:
      - 8080:8080
