version: "3.7"
services:
  submission-runner-docker:
    image: docker:dind
    privileged: true
    volumes:
      - "submission-runner-docker-certs:/certs/client"
      - "submission-runner-dind-data:/var/lib/docker"
    networks:
      submission-runner:
        aliases:
          - docker
    environment:
      - "DOCKER_TLS_CERTDIR=/certs"
    restart: unless-stopped
    init: true
  submission-runner:
    image: aiwarssoc/submission-runner
    volumes:
      - "repositories:/home/subrunner/repositories"
      - "submission-runner-docker-certs:/certs/client:ro"
    networks:
      - database
      - submission-runner
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    depends_on:
      - database
      - submission-runner-docker
    restart: unless-stopped
    init: true
  web-server:
    image: aiwarssoc/front-end
    volumes:
      - "repositories:/home/web_user/repositories"
    networks:
      - redis
      - database
    secrets:
      - secret_key
    depends_on:
      - database
      - redis
    restart: unless-stopped
  redis:
    image: redis
    volumes:
      - "redis-data:/data"
    command: "--appendonly yes"
    networks:
      redis:
        aliases:
          - redis
    restart: unless-stopped
  database:
    image: postgres
    volumes:
      - "database-data:/var/lib/postgresql/data"
    networks:
      database:
        aliases:
          - database
    restart: unless-stopped
  adminer:
    image: adminer
    networks:
      - database
    depends_on:
      - database
    restart: unless-stopped

networks:
  redis:
  database:
  submission-runner:
secrets:
  secret_key:
    file: ./secret.txt
volumes:
  repositories:
  redis-data:
  database-data:
  submission-runner-docker-certs:
  submission-runner-dind-data:
