version: "3.7"
services:
  submission-runner:
    volumes:
      - "./config.yml:/home/subrunner/config.yml:ro"
  web-server:
    ports:
      - "8090:8080"
    volumes:
      - "./config.yml:/home/web_user/config.yml:ro"
  database:
    environment:
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
  adminer:
    ports:
      - 8091:8080
