version: "3.7"
services:
  submission-runner:
    build: ./submission-runner
    image: aiwarssoc/submission-runner:debug
    volumes:
      - "./submission-runner/runner:/home/subrunner/runner"
      - "./submission-runner/sandbox:/home/subrunner/sandbox"
      - "./submission-runner/shared:/home/subrunner/shared"
    ports:
      - 8080:8080
  matchmaker:
    build: ./matchmaker
    image: aiwarssoc/matchmaker:debug
    volumes:
      - "./matchmaker/app:/home/matchmaker/app"
  web-server:
    build: ./web-server
    image: aiwarssoc/web-server:debug
    volumes:
      - "./web-server/serve:/usr/share/nginx/html"
      - "./logs/web-server/debug.log:/var/log/nginx/debug.log"
  web-app:
    build: web-app
    image: aiwarssoc/web-app:debug
    volumes:
      - "./web-app/app/dist:/usr/share/nginx/html:ro"
      - "./logs/web-app/debug.log:/var/log/nginx/debug.log"
  web-api:
    build: ./web-api
    image: aiwarssoc/web-api:debug
    volumes:
      - "./web-api/app:/home/web_user/app"
  adminer:
    depends_on:
      - database
    restart: unless-stopped
    init: true
    ports:
      - 8000:8080
