version: "3.7"
services:
  submission-runner:
    volumes:
      - "./config.yml:/home/subrunner/config.yml:ro"
  web-server:
    ports:
      - "8090:8080"
  matchmaker:
    volumes:
      - "./config.yml:/home/matchmaker/config.yml:ro"
  web-api:
    volumes:
      - "./config.yml:/home/web_user/config.yml:ro"
  web-app:
    volumes:
      - "./config.yml:/home/web_user/config.yml:ro"
  database:
    environment:
      POSTGRES_USER: release
      POSTGRES_PASSWORD: release
  adminer:
    ports:
      - 8091:8080
